<?php

namespace AppBundle\Repository;

use Doctrine\Common\Collections\Criteria;
use AppBundle\Entity\Order;

/**
 * CommissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommissionRepository extends \Doctrine\ORM\EntityRepository
{
	public function findDeadOrders()
	{
		$criteria = Criteria::create()->where(Criteria::expr()->eq('status', Order::$PAYMENT_NOT_CONFIRMED))
		->andWhere(Criteria::expr()->lte('dateTime', new \DateTime("-1 hour")));
		 
		return $this->matching($criteria);
	}
}
