<?php

namespace AppBundle\Repository;

/**
 * ImageItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageItemsRepository extends \Doctrine\ORM\EntityRepository
{
}
