<?php

namespace AppBundle\Repository;

/**
 * ShopCartGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopCartGameRepository extends \Doctrine\ORM\EntityRepository
{
}
