<?php

namespace AppBundle\Repository;

/**
 * ShopCartSellerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopCartSellerRepository extends \Doctrine\ORM\EntityRepository
{
}
