# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        seller_provider:
            entity:
                class: AppBundle:Seller
                property: username
        customer_provider:
            entity:
                class: AppBundle:Customer
                property: username
        admin_provider:
            entity:
                class: AppBundle:Admin
                property: username
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            pattern: ^/(?!(seller|customer|admin)).*$
            context: common_context
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            #form_login: 
            #    login_path: login
            #    check_path: login
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
        seller_firewall:
            pattern: ^/seller
            anonymous: ~
            #context: common_context
            form_login:
                login_path: /seller/login
                check_path: /seller/login
                default_target_path: seller_game_index
                always_use_default_target_path: true
            logout: 
                path: /seller/logout
                target: /games
                #invalidate_session: false
            provider: seller_provider

        customer_firewall:
            pattern: ^/customer
            anonymous: ~
            context: common_context
            form_login:
                login_path: /customer/login
                check_path: /customer/login
                #default_target_path: seller_game_index
                #always_use_default_target_path: true
            logout: 
                path: /customer/logout
                #invalidate_session: false
                target: /games
            provider: customer_provider
            
        admin_firewall:
            pattern: ^/admin
            anonymous: ~
            form_login:
                login_path: /admin/login
                check_path: /admin/login
                #default_target_path: seller_game_index
                #always_use_default_target_path: true
            logout: 
                path: /admin/logout
                #invalidate_session: false
                target: /games
            provider: admin_provider
    
    access_control:
        #- { path: ^/commission/\d+/{0,1}$, roles: [ROLE_SELLER, ROLE_CUSTOMER, ROLE_ADMIN] } #wrong!
        - { path: ^/seller/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/seller/new, roles: IS_AUTHENTICATED_ANONYMOUSLY }  
        - { path: ^/seller, roles: ROLE_SELLER }
        - { path: ^/customer/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/customer/new, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/customer, roles: ROLE_CUSTOMER }
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/new, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
                
    encoders:
        AppBundle\Entity\Seller: 
            algorithm: bcrypt
            cost: 12
        AppBundle\Entity\Customer: 
            algorithm: bcrypt
            cost: 12
        AppBundle\Entity\Admin: 
            algorithm: bcrypt
            cost: 12